package com.caocao.core.dao;

import com.caocao.core.model.Coupon;
import com.caocao.core.model.CouponExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    int countByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    int deleteByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    int insert(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    int insertSelective(Coupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    List<Coupon> selectByExample(CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") Coupon record, @Param("example") CouponExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_coupon
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    int updateByExample(@Param("record") Coupon record, @Param("example") CouponExample example);
}