package com.caocao.core.dao;

import com.caocao.core.model.CustomerBillInfo;
import com.caocao.core.model.CustomerBillInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerBillInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int countByExample(CustomerBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int deleteByExample(CustomerBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int insert(CustomerBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int insertSelective(CustomerBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    List<CustomerBillInfo> selectByExample(CustomerBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    CustomerBillInfo selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int updateByExampleSelective(@Param("record") CustomerBillInfo record, @Param("example") CustomerBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int updateByExample(@Param("record") CustomerBillInfo record, @Param("example") CustomerBillInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int updateByPrimaryKeySelective(CustomerBillInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_customer_bill_info
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    int updateByPrimaryKey(CustomerBillInfo record);
}