package com.caocao.core.dao;

import com.caocao.core.model.Custumer;
import com.caocao.core.model.CustumerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustumerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int countByExample(CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int deleteByExample(CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int insert(Custumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int insertSelective(Custumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    List<Custumer> selectByExampleWithBLOBs(CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    List<Custumer> selectByExample(CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    Custumer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") Custumer record, @Param("example") CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") Custumer record, @Param("example") CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int updateByExample(@Param("record") Custumer record, @Param("example") CustumerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int updateByPrimaryKeySelective(Custumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Custumer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_custumer
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    int updateByPrimaryKey(Custumer record);
}