package com.caocao.core.dao;

import com.caocao.core.model.Labour;
import com.caocao.core.model.Lease;
import com.caocao.core.model.LeaseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int countByExample(LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int deleteByExample(LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int insert(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int insertSelective(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    List<Lease> selectByExampleWithBLOBs(LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    List<Lease> selectByExample(LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    Lease selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int updateByExampleSelective(@Param("record") Lease record, @Param("example") LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") Lease record, @Param("example") LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int updateByExample(@Param("record") Lease record, @Param("example") LeaseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int updateByPrimaryKeySelective(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(Lease record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_lease
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    int updateByPrimaryKey(Lease record);
    
    List<Lease> QueryPageList(Lease record);
    
    Lease QueryOne(Lease record);
    
    Lease QueryById(Lease record);
}