package com.caocao.core.dao;

import com.caocao.core.model.Message;
import com.caocao.core.model.MessageExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    int countByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    int deleteByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    int insert(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    int insertSelective(Message record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    List<Message> selectByExample(MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") Message record, @Param("example") MessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_message
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    int updateByExample(@Param("record") Message record, @Param("example") MessageExample example);
}