package com.caocao.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class AdminExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public AdminExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNull() {
            addCriterion("_username is null");
            return (Criteria) this;
        }

        public Criteria andUsernameIsNotNull() {
            addCriterion("_username is not null");
            return (Criteria) this;
        }

        public Criteria andUsernameEqualTo(String value) {
            addCriterion("_username =", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotEqualTo(String value) {
            addCriterion("_username <>", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThan(String value) {
            addCriterion("_username >", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameGreaterThanOrEqualTo(String value) {
            addCriterion("_username >=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThan(String value) {
            addCriterion("_username <", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLessThanOrEqualTo(String value) {
            addCriterion("_username <=", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameLike(String value) {
            addCriterion("_username like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotLike(String value) {
            addCriterion("_username not like", value, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameIn(List<String> values) {
            addCriterion("_username in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotIn(List<String> values) {
            addCriterion("_username not in", values, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameBetween(String value1, String value2) {
            addCriterion("_username between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andUsernameNotBetween(String value1, String value2) {
            addCriterion("_username not between", value1, value2, "username");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNull() {
            addCriterion("_phone is null");
            return (Criteria) this;
        }

        public Criteria andPhoneIsNotNull() {
            addCriterion("_phone is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneEqualTo(String value) {
            addCriterion("_phone =", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotEqualTo(String value) {
            addCriterion("_phone <>", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThan(String value) {
            addCriterion("_phone >", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("_phone >=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThan(String value) {
            addCriterion("_phone <", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLessThanOrEqualTo(String value) {
            addCriterion("_phone <=", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneLike(String value) {
            addCriterion("_phone like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotLike(String value) {
            addCriterion("_phone not like", value, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneIn(List<String> values) {
            addCriterion("_phone in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotIn(List<String> values) {
            addCriterion("_phone not in", values, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneBetween(String value1, String value2) {
            addCriterion("_phone between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPhoneNotBetween(String value1, String value2) {
            addCriterion("_phone not between", value1, value2, "phone");
            return (Criteria) this;
        }

        public Criteria andPswIsNull() {
            addCriterion("_psw is null");
            return (Criteria) this;
        }

        public Criteria andPswIsNotNull() {
            addCriterion("_psw is not null");
            return (Criteria) this;
        }

        public Criteria andPswEqualTo(String value) {
            addCriterion("_psw =", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswNotEqualTo(String value) {
            addCriterion("_psw <>", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswGreaterThan(String value) {
            addCriterion("_psw >", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswGreaterThanOrEqualTo(String value) {
            addCriterion("_psw >=", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswLessThan(String value) {
            addCriterion("_psw <", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswLessThanOrEqualTo(String value) {
            addCriterion("_psw <=", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswLike(String value) {
            addCriterion("_psw like", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswNotLike(String value) {
            addCriterion("_psw not like", value, "psw");
            return (Criteria) this;
        }

        public Criteria andPswIn(List<String> values) {
            addCriterion("_psw in", values, "psw");
            return (Criteria) this;
        }

        public Criteria andPswNotIn(List<String> values) {
            addCriterion("_psw not in", values, "psw");
            return (Criteria) this;
        }

        public Criteria andPswBetween(String value1, String value2) {
            addCriterion("_psw between", value1, value2, "psw");
            return (Criteria) this;
        }

        public Criteria andPswNotBetween(String value1, String value2) {
            addCriterion("_psw not between", value1, value2, "psw");
            return (Criteria) this;
        }

        public Criteria andPostIsNull() {
            addCriterion("_post is null");
            return (Criteria) this;
        }

        public Criteria andPostIsNotNull() {
            addCriterion("_post is not null");
            return (Criteria) this;
        }

        public Criteria andPostEqualTo(String value) {
            addCriterion("_post =", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotEqualTo(String value) {
            addCriterion("_post <>", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostGreaterThan(String value) {
            addCriterion("_post >", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostGreaterThanOrEqualTo(String value) {
            addCriterion("_post >=", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLessThan(String value) {
            addCriterion("_post <", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLessThanOrEqualTo(String value) {
            addCriterion("_post <=", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostLike(String value) {
            addCriterion("_post like", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotLike(String value) {
            addCriterion("_post not like", value, "post");
            return (Criteria) this;
        }

        public Criteria andPostIn(List<String> values) {
            addCriterion("_post in", values, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotIn(List<String> values) {
            addCriterion("_post not in", values, "post");
            return (Criteria) this;
        }

        public Criteria andPostBetween(String value1, String value2) {
            addCriterion("_post between", value1, value2, "post");
            return (Criteria) this;
        }

        public Criteria andPostNotBetween(String value1, String value2) {
            addCriterion("_post not between", value1, value2, "post");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNull() {
            addCriterion("_isActive is null");
            return (Criteria) this;
        }

        public Criteria andIsactiveIsNotNull() {
            addCriterion("_isActive is not null");
            return (Criteria) this;
        }

        public Criteria andIsactiveEqualTo(Integer value) {
            addCriterion("_isActive =", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotEqualTo(Integer value) {
            addCriterion("_isActive <>", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThan(Integer value) {
            addCriterion("_isActive >", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveGreaterThanOrEqualTo(Integer value) {
            addCriterion("_isActive >=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThan(Integer value) {
            addCriterion("_isActive <", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveLessThanOrEqualTo(Integer value) {
            addCriterion("_isActive <=", value, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveIn(List<Integer> values) {
            addCriterion("_isActive in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotIn(List<Integer> values) {
            addCriterion("_isActive not in", values, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveBetween(Integer value1, Integer value2) {
            addCriterion("_isActive between", value1, value2, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactiveNotBetween(Integer value1, Integer value2) {
            addCriterion("_isActive not between", value1, value2, "isactive");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeIsNull() {
            addCriterion("_isActiveTime is null");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeIsNotNull() {
            addCriterion("_isActiveTime is not null");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeEqualTo(Date value) {
            addCriterion("_isActiveTime =", value, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeNotEqualTo(Date value) {
            addCriterion("_isActiveTime <>", value, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeGreaterThan(Date value) {
            addCriterion("_isActiveTime >", value, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_isActiveTime >=", value, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeLessThan(Date value) {
            addCriterion("_isActiveTime <", value, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeLessThanOrEqualTo(Date value) {
            addCriterion("_isActiveTime <=", value, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeIn(List<Date> values) {
            addCriterion("_isActiveTime in", values, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeNotIn(List<Date> values) {
            addCriterion("_isActiveTime not in", values, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeBetween(Date value1, Date value2) {
            addCriterion("_isActiveTime between", value1, value2, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andIsactivetimeNotBetween(Date value1, Date value2) {
            addCriterion("_isActiveTime not between", value1, value2, "isactivetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeIsNull() {
            addCriterion("_freezeTime is null");
            return (Criteria) this;
        }

        public Criteria andFreezetimeIsNotNull() {
            addCriterion("_freezeTime is not null");
            return (Criteria) this;
        }

        public Criteria andFreezetimeEqualTo(Date value) {
            addCriterion("_freezeTime =", value, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeNotEqualTo(Date value) {
            addCriterion("_freezeTime <>", value, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeGreaterThan(Date value) {
            addCriterion("_freezeTime >", value, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_freezeTime >=", value, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeLessThan(Date value) {
            addCriterion("_freezeTime <", value, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeLessThanOrEqualTo(Date value) {
            addCriterion("_freezeTime <=", value, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeIn(List<Date> values) {
            addCriterion("_freezeTime in", values, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeNotIn(List<Date> values) {
            addCriterion("_freezeTime not in", values, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeBetween(Date value1, Date value2) {
            addCriterion("_freezeTime between", value1, value2, "freezetime");
            return (Criteria) this;
        }

        public Criteria andFreezetimeNotBetween(Date value1, Date value2) {
            addCriterion("_freezeTime not between", value1, value2, "freezetime");
            return (Criteria) this;
        }

        public Criteria andLogintimeIsNull() {
            addCriterion("_loginTime is null");
            return (Criteria) this;
        }

        public Criteria andLogintimeIsNotNull() {
            addCriterion("_loginTime is not null");
            return (Criteria) this;
        }

        public Criteria andLogintimeEqualTo(Date value) {
            addCriterion("_loginTime =", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotEqualTo(Date value) {
            addCriterion("_loginTime <>", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeGreaterThan(Date value) {
            addCriterion("_loginTime >", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_loginTime >=", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeLessThan(Date value) {
            addCriterion("_loginTime <", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeLessThanOrEqualTo(Date value) {
            addCriterion("_loginTime <=", value, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeIn(List<Date> values) {
            addCriterion("_loginTime in", values, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotIn(List<Date> values) {
            addCriterion("_loginTime not in", values, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeBetween(Date value1, Date value2) {
            addCriterion("_loginTime between", value1, value2, "logintime");
            return (Criteria) this;
        }

        public Criteria andLogintimeNotBetween(Date value1, Date value2) {
            addCriterion("_loginTime not between", value1, value2, "logintime");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("_company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("_company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("_company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("_company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("_company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("_company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("_company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("_company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("_company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("_company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("_company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("_company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("_company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("_createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("_createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("_createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("_createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("_createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("_createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("_createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("_createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("_createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("_createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("_updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("_updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("_updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("_updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("_updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("_updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("_updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("_updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("_updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateIsNull() {
            addCriterion("_author_update is null");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateIsNotNull() {
            addCriterion("_author_update is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateEqualTo(String value) {
            addCriterion("_author_update =", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotEqualTo(String value) {
            addCriterion("_author_update <>", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateGreaterThan(String value) {
            addCriterion("_author_update >", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateGreaterThanOrEqualTo(String value) {
            addCriterion("_author_update >=", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateLessThan(String value) {
            addCriterion("_author_update <", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateLessThanOrEqualTo(String value) {
            addCriterion("_author_update <=", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateLike(String value) {
            addCriterion("_author_update like", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotLike(String value) {
            addCriterion("_author_update not like", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateIn(List<String> values) {
            addCriterion("_author_update in", values, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotIn(List<String> values) {
            addCriterion("_author_update not in", values, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateBetween(String value1, String value2) {
            addCriterion("_author_update between", value1, value2, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotBetween(String value1, String value2) {
            addCriterion("_author_update not between", value1, value2, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("_version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("_version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Double value) {
            addCriterion("_version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Double value) {
            addCriterion("_version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Double value) {
            addCriterion("_version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Double value) {
            addCriterion("_version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Double value) {
            addCriterion("_version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Double value) {
            addCriterion("_version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Double> values) {
            addCriterion("_version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Double> values) {
            addCriterion("_version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Double value1, Double value2) {
            addCriterion("_version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Double value1, Double value2) {
            addCriterion("_version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated do_not_delete_during_merge Tue Jun 16 10:42:40 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tsp_caocao_admin
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}