package com.caocao.core.model;

public class Bank {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_bank._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_bank._agent_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String agentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_bank._number
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_bank._pay_method
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer payMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_bank._account_type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer accountType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_bank._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_bank._id
     *
     * @return the value of tsp_caocao_bank._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_bank._id
     *
     * @param id the value for tsp_caocao_bank._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_bank._agent_id
     *
     * @return the value of tsp_caocao_bank._agent_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getAgentId() {
        return agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_bank._agent_id
     *
     * @param agentId the value for tsp_caocao_bank._agent_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAgentId(String agentId) {
        this.agentId = agentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_bank._number
     *
     * @return the value of tsp_caocao_bank._number
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_bank._number
     *
     * @param number the value for tsp_caocao_bank._number
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_bank._pay_method
     *
     * @return the value of tsp_caocao_bank._pay_method
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getPayMethod() {
        return payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_bank._pay_method
     *
     * @param payMethod the value for tsp_caocao_bank._pay_method
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setPayMethod(Integer payMethod) {
        this.payMethod = payMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_bank._account_type
     *
     * @return the value of tsp_caocao_bank._account_type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getAccountType() {
        return accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_bank._account_type
     *
     * @param accountType the value for tsp_caocao_bank._account_type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAccountType(Integer accountType) {
        this.accountType = accountType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_bank._version
     *
     * @return the value of tsp_caocao_bank._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_bank._version
     *
     * @param version the value for tsp_caocao_bank._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}