package com.caocao.core.model;

import java.util.Date;

public class Car {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._number
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String number;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._service
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer service;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._age
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._driver_license_no
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String driverLicenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._insurance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String insurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._bus_insurance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String busInsurance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._driver_km
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Long driverKm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._lease_company
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer leaseCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._updatetime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._author_create
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String authorCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._author_update
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String authorUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._current_status
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer currentStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._city
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._color
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String color;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._id
     *
     * @return the value of tsp_caocao_car._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._id
     *
     * @param id the value for tsp_caocao_car._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._number
     *
     * @return the value of tsp_caocao_car._number
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getNumber() {
        return number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._number
     *
     * @param number the value for tsp_caocao_car._number
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setNumber(String number) {
        this.number = number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._type
     *
     * @return the value of tsp_caocao_car._type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._type
     *
     * @param type the value for tsp_caocao_car._type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._service
     *
     * @return the value of tsp_caocao_car._service
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getService() {
        return service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._service
     *
     * @param service the value for tsp_caocao_car._service
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setService(Integer service) {
        this.service = service;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._age
     *
     * @return the value of tsp_caocao_car._age
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._age
     *
     * @param age the value for tsp_caocao_car._age
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._driver_license_no
     *
     * @return the value of tsp_caocao_car._driver_license_no
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getDriverLicenseNo() {
        return driverLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._driver_license_no
     *
     * @param driverLicenseNo the value for tsp_caocao_car._driver_license_no
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDriverLicenseNo(String driverLicenseNo) {
        this.driverLicenseNo = driverLicenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._insurance
     *
     * @return the value of tsp_caocao_car._insurance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getInsurance() {
        return insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._insurance
     *
     * @param insurance the value for tsp_caocao_car._insurance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setInsurance(String insurance) {
        this.insurance = insurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._bus_insurance
     *
     * @return the value of tsp_caocao_car._bus_insurance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getBusInsurance() {
        return busInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._bus_insurance
     *
     * @param busInsurance the value for tsp_caocao_car._bus_insurance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setBusInsurance(String busInsurance) {
        this.busInsurance = busInsurance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._driver_km
     *
     * @return the value of tsp_caocao_car._driver_km
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Long getDriverKm() {
        return driverKm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._driver_km
     *
     * @param driverKm the value for tsp_caocao_car._driver_km
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDriverKm(Long driverKm) {
        this.driverKm = driverKm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._lease_company
     *
     * @return the value of tsp_caocao_car._lease_company
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getLeaseCompany() {
        return leaseCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._lease_company
     *
     * @param leaseCompany the value for tsp_caocao_car._lease_company
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setLeaseCompany(Integer leaseCompany) {
        this.leaseCompany = leaseCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._createtime
     *
     * @return the value of tsp_caocao_car._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._createtime
     *
     * @param createtime the value for tsp_caocao_car._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._updatetime
     *
     * @return the value of tsp_caocao_car._updatetime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._updatetime
     *
     * @param updatetime the value for tsp_caocao_car._updatetime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._author_create
     *
     * @return the value of tsp_caocao_car._author_create
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getAuthorCreate() {
        return authorCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._author_create
     *
     * @param authorCreate the value for tsp_caocao_car._author_create
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAuthorCreate(String authorCreate) {
        this.authorCreate = authorCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._author_update
     *
     * @return the value of tsp_caocao_car._author_update
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getAuthorUpdate() {
        return authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._author_update
     *
     * @param authorUpdate the value for tsp_caocao_car._author_update
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAuthorUpdate(String authorUpdate) {
        this.authorUpdate = authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._current_status
     *
     * @return the value of tsp_caocao_car._current_status
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getCurrentStatus() {
        return currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._current_status
     *
     * @param currentStatus the value for tsp_caocao_car._current_status
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCurrentStatus(Integer currentStatus) {
        this.currentStatus = currentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._city
     *
     * @return the value of tsp_caocao_car._city
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._city
     *
     * @param city the value for tsp_caocao_car._city
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._color
     *
     * @return the value of tsp_caocao_car._color
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getColor() {
        return color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._color
     *
     * @param color the value for tsp_caocao_car._color
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setColor(String color) {
        this.color = color;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car._version
     *
     * @return the value of tsp_caocao_car._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car._version
     *
     * @param version the value for tsp_caocao_car._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}