package com.caocao.core.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CarExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public CarExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("_id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("_id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("_id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("_id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("_id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("_id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("_id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("_id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("_id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("_id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("_id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("_id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNumberIsNull() {
            addCriterion("_number is null");
            return (Criteria) this;
        }

        public Criteria andNumberIsNotNull() {
            addCriterion("_number is not null");
            return (Criteria) this;
        }

        public Criteria andNumberEqualTo(String value) {
            addCriterion("_number =", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotEqualTo(String value) {
            addCriterion("_number <>", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThan(String value) {
            addCriterion("_number >", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberGreaterThanOrEqualTo(String value) {
            addCriterion("_number >=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThan(String value) {
            addCriterion("_number <", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLessThanOrEqualTo(String value) {
            addCriterion("_number <=", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberLike(String value) {
            addCriterion("_number like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotLike(String value) {
            addCriterion("_number not like", value, "number");
            return (Criteria) this;
        }

        public Criteria andNumberIn(List<String> values) {
            addCriterion("_number in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotIn(List<String> values) {
            addCriterion("_number not in", values, "number");
            return (Criteria) this;
        }

        public Criteria andNumberBetween(String value1, String value2) {
            addCriterion("_number between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andNumberNotBetween(String value1, String value2) {
            addCriterion("_number not between", value1, value2, "number");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("_type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("_type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("_type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("_type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("_type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("_type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("_type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("_type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("_type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("_type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("_type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("_type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("_type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("_type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andServiceIsNull() {
            addCriterion("_service is null");
            return (Criteria) this;
        }

        public Criteria andServiceIsNotNull() {
            addCriterion("_service is not null");
            return (Criteria) this;
        }

        public Criteria andServiceEqualTo(Integer value) {
            addCriterion("_service =", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotEqualTo(Integer value) {
            addCriterion("_service <>", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThan(Integer value) {
            addCriterion("_service >", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceGreaterThanOrEqualTo(Integer value) {
            addCriterion("_service >=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThan(Integer value) {
            addCriterion("_service <", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceLessThanOrEqualTo(Integer value) {
            addCriterion("_service <=", value, "service");
            return (Criteria) this;
        }

        public Criteria andServiceIn(List<Integer> values) {
            addCriterion("_service in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotIn(List<Integer> values) {
            addCriterion("_service not in", values, "service");
            return (Criteria) this;
        }

        public Criteria andServiceBetween(Integer value1, Integer value2) {
            addCriterion("_service between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andServiceNotBetween(Integer value1, Integer value2) {
            addCriterion("_service not between", value1, value2, "service");
            return (Criteria) this;
        }

        public Criteria andAgeIsNull() {
            addCriterion("_age is null");
            return (Criteria) this;
        }

        public Criteria andAgeIsNotNull() {
            addCriterion("_age is not null");
            return (Criteria) this;
        }

        public Criteria andAgeEqualTo(Integer value) {
            addCriterion("_age =", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotEqualTo(Integer value) {
            addCriterion("_age <>", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThan(Integer value) {
            addCriterion("_age >", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeGreaterThanOrEqualTo(Integer value) {
            addCriterion("_age >=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThan(Integer value) {
            addCriterion("_age <", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeLessThanOrEqualTo(Integer value) {
            addCriterion("_age <=", value, "age");
            return (Criteria) this;
        }

        public Criteria andAgeIn(List<Integer> values) {
            addCriterion("_age in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotIn(List<Integer> values) {
            addCriterion("_age not in", values, "age");
            return (Criteria) this;
        }

        public Criteria andAgeBetween(Integer value1, Integer value2) {
            addCriterion("_age between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andAgeNotBetween(Integer value1, Integer value2) {
            addCriterion("_age not between", value1, value2, "age");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoIsNull() {
            addCriterion("_driver_license_no is null");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoIsNotNull() {
            addCriterion("_driver_license_no is not null");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoEqualTo(String value) {
            addCriterion("_driver_license_no =", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoNotEqualTo(String value) {
            addCriterion("_driver_license_no <>", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoGreaterThan(String value) {
            addCriterion("_driver_license_no >", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoGreaterThanOrEqualTo(String value) {
            addCriterion("_driver_license_no >=", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoLessThan(String value) {
            addCriterion("_driver_license_no <", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoLessThanOrEqualTo(String value) {
            addCriterion("_driver_license_no <=", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoLike(String value) {
            addCriterion("_driver_license_no like", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoNotLike(String value) {
            addCriterion("_driver_license_no not like", value, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoIn(List<String> values) {
            addCriterion("_driver_license_no in", values, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoNotIn(List<String> values) {
            addCriterion("_driver_license_no not in", values, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoBetween(String value1, String value2) {
            addCriterion("_driver_license_no between", value1, value2, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andDriverLicenseNoNotBetween(String value1, String value2) {
            addCriterion("_driver_license_no not between", value1, value2, "driverLicenseNo");
            return (Criteria) this;
        }

        public Criteria andInsuranceIsNull() {
            addCriterion("_insurance is null");
            return (Criteria) this;
        }

        public Criteria andInsuranceIsNotNull() {
            addCriterion("_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andInsuranceEqualTo(String value) {
            addCriterion("_insurance =", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotEqualTo(String value) {
            addCriterion("_insurance <>", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceGreaterThan(String value) {
            addCriterion("_insurance >", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("_insurance >=", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceLessThan(String value) {
            addCriterion("_insurance <", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceLessThanOrEqualTo(String value) {
            addCriterion("_insurance <=", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceLike(String value) {
            addCriterion("_insurance like", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotLike(String value) {
            addCriterion("_insurance not like", value, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceIn(List<String> values) {
            addCriterion("_insurance in", values, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotIn(List<String> values) {
            addCriterion("_insurance not in", values, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceBetween(String value1, String value2) {
            addCriterion("_insurance between", value1, value2, "insurance");
            return (Criteria) this;
        }

        public Criteria andInsuranceNotBetween(String value1, String value2) {
            addCriterion("_insurance not between", value1, value2, "insurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceIsNull() {
            addCriterion("_bus_insurance is null");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceIsNotNull() {
            addCriterion("_bus_insurance is not null");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceEqualTo(String value) {
            addCriterion("_bus_insurance =", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceNotEqualTo(String value) {
            addCriterion("_bus_insurance <>", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceGreaterThan(String value) {
            addCriterion("_bus_insurance >", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceGreaterThanOrEqualTo(String value) {
            addCriterion("_bus_insurance >=", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceLessThan(String value) {
            addCriterion("_bus_insurance <", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceLessThanOrEqualTo(String value) {
            addCriterion("_bus_insurance <=", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceLike(String value) {
            addCriterion("_bus_insurance like", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceNotLike(String value) {
            addCriterion("_bus_insurance not like", value, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceIn(List<String> values) {
            addCriterion("_bus_insurance in", values, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceNotIn(List<String> values) {
            addCriterion("_bus_insurance not in", values, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceBetween(String value1, String value2) {
            addCriterion("_bus_insurance between", value1, value2, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andBusInsuranceNotBetween(String value1, String value2) {
            addCriterion("_bus_insurance not between", value1, value2, "busInsurance");
            return (Criteria) this;
        }

        public Criteria andDriverKmIsNull() {
            addCriterion("_driver_km is null");
            return (Criteria) this;
        }

        public Criteria andDriverKmIsNotNull() {
            addCriterion("_driver_km is not null");
            return (Criteria) this;
        }

        public Criteria andDriverKmEqualTo(Long value) {
            addCriterion("_driver_km =", value, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmNotEqualTo(Long value) {
            addCriterion("_driver_km <>", value, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmGreaterThan(Long value) {
            addCriterion("_driver_km >", value, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmGreaterThanOrEqualTo(Long value) {
            addCriterion("_driver_km >=", value, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmLessThan(Long value) {
            addCriterion("_driver_km <", value, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmLessThanOrEqualTo(Long value) {
            addCriterion("_driver_km <=", value, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmIn(List<Long> values) {
            addCriterion("_driver_km in", values, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmNotIn(List<Long> values) {
            addCriterion("_driver_km not in", values, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmBetween(Long value1, Long value2) {
            addCriterion("_driver_km between", value1, value2, "driverKm");
            return (Criteria) this;
        }

        public Criteria andDriverKmNotBetween(Long value1, Long value2) {
            addCriterion("_driver_km not between", value1, value2, "driverKm");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyIsNull() {
            addCriterion("_lease_company is null");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyIsNotNull() {
            addCriterion("_lease_company is not null");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyEqualTo(Integer value) {
            addCriterion("_lease_company =", value, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyNotEqualTo(Integer value) {
            addCriterion("_lease_company <>", value, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyGreaterThan(Integer value) {
            addCriterion("_lease_company >", value, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyGreaterThanOrEqualTo(Integer value) {
            addCriterion("_lease_company >=", value, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyLessThan(Integer value) {
            addCriterion("_lease_company <", value, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyLessThanOrEqualTo(Integer value) {
            addCriterion("_lease_company <=", value, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyIn(List<Integer> values) {
            addCriterion("_lease_company in", values, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyNotIn(List<Integer> values) {
            addCriterion("_lease_company not in", values, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyBetween(Integer value1, Integer value2) {
            addCriterion("_lease_company between", value1, value2, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andLeaseCompanyNotBetween(Integer value1, Integer value2) {
            addCriterion("_lease_company not between", value1, value2, "leaseCompany");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("_createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("_createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("_createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("_createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("_createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("_createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("_createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("_createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("_createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("_createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("_createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("_updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("_updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("_updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("_updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("_updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("_updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("_updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("_updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("_updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("_updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("_updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("_updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateIsNull() {
            addCriterion("_author_create is null");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateIsNotNull() {
            addCriterion("_author_create is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateEqualTo(String value) {
            addCriterion("_author_create =", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateNotEqualTo(String value) {
            addCriterion("_author_create <>", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateGreaterThan(String value) {
            addCriterion("_author_create >", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateGreaterThanOrEqualTo(String value) {
            addCriterion("_author_create >=", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateLessThan(String value) {
            addCriterion("_author_create <", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateLessThanOrEqualTo(String value) {
            addCriterion("_author_create <=", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateLike(String value) {
            addCriterion("_author_create like", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateNotLike(String value) {
            addCriterion("_author_create not like", value, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateIn(List<String> values) {
            addCriterion("_author_create in", values, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateNotIn(List<String> values) {
            addCriterion("_author_create not in", values, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateBetween(String value1, String value2) {
            addCriterion("_author_create between", value1, value2, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorCreateNotBetween(String value1, String value2) {
            addCriterion("_author_create not between", value1, value2, "authorCreate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateIsNull() {
            addCriterion("_author_update is null");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateIsNotNull() {
            addCriterion("_author_update is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateEqualTo(String value) {
            addCriterion("_author_update =", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotEqualTo(String value) {
            addCriterion("_author_update <>", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateGreaterThan(String value) {
            addCriterion("_author_update >", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateGreaterThanOrEqualTo(String value) {
            addCriterion("_author_update >=", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateLessThan(String value) {
            addCriterion("_author_update <", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateLessThanOrEqualTo(String value) {
            addCriterion("_author_update <=", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateLike(String value) {
            addCriterion("_author_update like", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotLike(String value) {
            addCriterion("_author_update not like", value, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateIn(List<String> values) {
            addCriterion("_author_update in", values, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotIn(List<String> values) {
            addCriterion("_author_update not in", values, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateBetween(String value1, String value2) {
            addCriterion("_author_update between", value1, value2, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andAuthorUpdateNotBetween(String value1, String value2) {
            addCriterion("_author_update not between", value1, value2, "authorUpdate");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusIsNull() {
            addCriterion("_current_status is null");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusIsNotNull() {
            addCriterion("_current_status is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusEqualTo(Integer value) {
            addCriterion("_current_status =", value, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusNotEqualTo(Integer value) {
            addCriterion("_current_status <>", value, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusGreaterThan(Integer value) {
            addCriterion("_current_status >", value, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("_current_status >=", value, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusLessThan(Integer value) {
            addCriterion("_current_status <", value, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusLessThanOrEqualTo(Integer value) {
            addCriterion("_current_status <=", value, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusIn(List<Integer> values) {
            addCriterion("_current_status in", values, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusNotIn(List<Integer> values) {
            addCriterion("_current_status not in", values, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusBetween(Integer value1, Integer value2) {
            addCriterion("_current_status between", value1, value2, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCurrentStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("_current_status not between", value1, value2, "currentStatus");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("_city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("_city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("_city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("_city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("_city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("_city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("_city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("_city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("_city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("_city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("_city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("_city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("_city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("_city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andColorIsNull() {
            addCriterion("_color is null");
            return (Criteria) this;
        }

        public Criteria andColorIsNotNull() {
            addCriterion("_color is not null");
            return (Criteria) this;
        }

        public Criteria andColorEqualTo(String value) {
            addCriterion("_color =", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotEqualTo(String value) {
            addCriterion("_color <>", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThan(String value) {
            addCriterion("_color >", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorGreaterThanOrEqualTo(String value) {
            addCriterion("_color >=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThan(String value) {
            addCriterion("_color <", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLessThanOrEqualTo(String value) {
            addCriterion("_color <=", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorLike(String value) {
            addCriterion("_color like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotLike(String value) {
            addCriterion("_color not like", value, "color");
            return (Criteria) this;
        }

        public Criteria andColorIn(List<String> values) {
            addCriterion("_color in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotIn(List<String> values) {
            addCriterion("_color not in", values, "color");
            return (Criteria) this;
        }

        public Criteria andColorBetween(String value1, String value2) {
            addCriterion("_color between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andColorNotBetween(String value1, String value2) {
            addCriterion("_color not between", value1, value2, "color");
            return (Criteria) this;
        }

        public Criteria andVersionIsNull() {
            addCriterion("_version is null");
            return (Criteria) this;
        }

        public Criteria andVersionIsNotNull() {
            addCriterion("_version is not null");
            return (Criteria) this;
        }

        public Criteria andVersionEqualTo(Double value) {
            addCriterion("_version =", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotEqualTo(Double value) {
            addCriterion("_version <>", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThan(Double value) {
            addCriterion("_version >", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionGreaterThanOrEqualTo(Double value) {
            addCriterion("_version >=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThan(Double value) {
            addCriterion("_version <", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionLessThanOrEqualTo(Double value) {
            addCriterion("_version <=", value, "version");
            return (Criteria) this;
        }

        public Criteria andVersionIn(List<Double> values) {
            addCriterion("_version in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotIn(List<Double> values) {
            addCriterion("_version not in", values, "version");
            return (Criteria) this;
        }

        public Criteria andVersionBetween(Double value1, Double value2) {
            addCriterion("_version between", value1, value2, "version");
            return (Criteria) this;
        }

        public Criteria andVersionNotBetween(Double value1, Double value2) {
            addCriterion("_version not between", value1, value2, "version");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 10 11:11:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tsp_caocao_car
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}