package com.caocao.core.model;

public class CarPhoto {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car_photo._car_id
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car_photo._photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car_photo._front_license_photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    private String frontLicensePhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_car_photo._back_license_photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    private String backLicensePhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car_photo._car_id
     *
     * @return the value of tsp_caocao_car_photo._car_id
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car_photo._car_id
     *
     * @param carId the value for tsp_caocao_car_photo._car_id
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car_photo._photo
     *
     * @return the value of tsp_caocao_car_photo._photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car_photo._photo
     *
     * @param photo the value for tsp_caocao_car_photo._photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car_photo._front_license_photo
     *
     * @return the value of tsp_caocao_car_photo._front_license_photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public String getFrontLicensePhoto() {
        return frontLicensePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car_photo._front_license_photo
     *
     * @param frontLicensePhoto the value for tsp_caocao_car_photo._front_license_photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public void setFrontLicensePhoto(String frontLicensePhoto) {
        this.frontLicensePhoto = frontLicensePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_car_photo._back_license_photo
     *
     * @return the value of tsp_caocao_car_photo._back_license_photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public String getBackLicensePhoto() {
        return backLicensePhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_car_photo._back_license_photo
     *
     * @param backLicensePhoto the value for tsp_caocao_car_photo._back_license_photo
     *
     * @mbggenerated Wed Jun 17 23:27:14 CST 2015
     */
    public void setBackLicensePhoto(String backLicensePhoto) {
        this.backLicensePhoto = backLicensePhoto;
    }
}