package com.caocao.core.model;

import java.util.Date;

public class Carrelation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._driver_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._car_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer carId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._createtime
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._updatetime
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._author_create
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private String authorCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._author_update
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private String authorUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._is_default
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer isDefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_car_relation._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._id
     *
     * @return the value of tsp_caocao_driver_car_relation._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._id
     *
     * @param id the value for tsp_caocao_driver_car_relation._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._driver_id
     *
     * @return the value of tsp_caocao_driver_car_relation._driver_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._driver_id
     *
     * @param driverId the value for tsp_caocao_driver_car_relation._driver_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._car_id
     *
     * @return the value of tsp_caocao_driver_car_relation._car_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getCarId() {
        return carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._car_id
     *
     * @param carId the value for tsp_caocao_driver_car_relation._car_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setCarId(Integer carId) {
        this.carId = carId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._createtime
     *
     * @return the value of tsp_caocao_driver_car_relation._createtime
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._createtime
     *
     * @param createtime the value for tsp_caocao_driver_car_relation._createtime
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._updatetime
     *
     * @return the value of tsp_caocao_driver_car_relation._updatetime
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._updatetime
     *
     * @param updatetime the value for tsp_caocao_driver_car_relation._updatetime
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._author_create
     *
     * @return the value of tsp_caocao_driver_car_relation._author_create
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public String getAuthorCreate() {
        return authorCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._author_create
     *
     * @param authorCreate the value for tsp_caocao_driver_car_relation._author_create
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setAuthorCreate(String authorCreate) {
        this.authorCreate = authorCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._author_update
     *
     * @return the value of tsp_caocao_driver_car_relation._author_update
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public String getAuthorUpdate() {
        return authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._author_update
     *
     * @param authorUpdate the value for tsp_caocao_driver_car_relation._author_update
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setAuthorUpdate(String authorUpdate) {
        this.authorUpdate = authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._is_default
     *
     * @return the value of tsp_caocao_driver_car_relation._is_default
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getIsDefault() {
        return isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._is_default
     *
     * @param isDefault the value for tsp_caocao_driver_car_relation._is_default
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setIsDefault(Integer isDefault) {
        this.isDefault = isDefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_car_relation._version
     *
     * @return the value of tsp_caocao_driver_car_relation._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_car_relation._version
     *
     * @param version the value for tsp_caocao_driver_car_relation._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}