package com.caocao.core.model;

public class Constant {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_constant._name
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_constant._value
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    private String value;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_constant._version
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_constant._name
     *
     * @return the value of tsp_caocao_constant._name
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_constant._name
     *
     * @param name the value for tsp_caocao_constant._name
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_constant._value
     *
     * @return the value of tsp_caocao_constant._value
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    public String getValue() {
        return value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_constant._value
     *
     * @param value the value for tsp_caocao_constant._value
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    public void setValue(String value) {
        this.value = value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_constant._version
     *
     * @return the value of tsp_caocao_constant._version
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_constant._version
     *
     * @param version the value for tsp_caocao_constant._version
     *
     * @mbggenerated Fri Jun 05 15:26:33 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}