package com.caocao.core.model;

import java.util.Date;

public class Coupon {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_coupon._id
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_coupon._num
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    private String num;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_coupon._money
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    private Double money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_coupon._effective_begin
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    private Date effectiveBegin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_coupon._effective_end
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    private Date effectiveEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_coupon._customer_id
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    private Integer customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_coupon._id
     *
     * @return the value of tsp_caocao_coupon._id
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_coupon._id
     *
     * @param id the value for tsp_caocao_coupon._id
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_coupon._num
     *
     * @return the value of tsp_caocao_coupon._num
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public String getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_coupon._num
     *
     * @param num the value for tsp_caocao_coupon._num
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public void setNum(String num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_coupon._money
     *
     * @return the value of tsp_caocao_coupon._money
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_coupon._money
     *
     * @param money the value for tsp_caocao_coupon._money
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_coupon._effective_begin
     *
     * @return the value of tsp_caocao_coupon._effective_begin
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public Date getEffectiveBegin() {
        return effectiveBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_coupon._effective_begin
     *
     * @param effectiveBegin the value for tsp_caocao_coupon._effective_begin
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public void setEffectiveBegin(Date effectiveBegin) {
        this.effectiveBegin = effectiveBegin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_coupon._effective_end
     *
     * @return the value of tsp_caocao_coupon._effective_end
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public Date getEffectiveEnd() {
        return effectiveEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_coupon._effective_end
     *
     * @param effectiveEnd the value for tsp_caocao_coupon._effective_end
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public void setEffectiveEnd(Date effectiveEnd) {
        this.effectiveEnd = effectiveEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_coupon._customer_id
     *
     * @return the value of tsp_caocao_coupon._customer_id
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_coupon._customer_id
     *
     * @param customerId the value for tsp_caocao_coupon._customer_id
     *
     * @mbggenerated Tue Jun 16 15:48:53 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }
}