package com.caocao.core.model;

import java.util.Date;

public class Custumer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._email
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._phone
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._first_name
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String firstName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._last_name
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String lastName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._photo
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String photo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._nickName
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._sex
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._updatetime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._author_update
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String authorUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._last_login_time
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Date lastLoginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._company
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String company;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._company_address
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._company_require
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer companyRequire;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._invite_code
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String inviteCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._citycode
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer citycode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._areacode
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Integer areacode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_custumer._remark
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._id
     *
     * @return the value of tsp_caocao_custumer._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._id
     *
     * @param id the value for tsp_caocao_custumer._id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._email
     *
     * @return the value of tsp_caocao_custumer._email
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._email
     *
     * @param email the value for tsp_caocao_custumer._email
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._phone
     *
     * @return the value of tsp_caocao_custumer._phone
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._phone
     *
     * @param phone the value for tsp_caocao_custumer._phone
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._first_name
     *
     * @return the value of tsp_caocao_custumer._first_name
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._first_name
     *
     * @param firstName the value for tsp_caocao_custumer._first_name
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._last_name
     *
     * @return the value of tsp_caocao_custumer._last_name
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._last_name
     *
     * @param lastName the value for tsp_caocao_custumer._last_name
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._photo
     *
     * @return the value of tsp_caocao_custumer._photo
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._photo
     *
     * @param photo the value for tsp_caocao_custumer._photo
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._nickName
     *
     * @return the value of tsp_caocao_custumer._nickName
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._nickName
     *
     * @param nickname the value for tsp_caocao_custumer._nickName
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._sex
     *
     * @return the value of tsp_caocao_custumer._sex
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._sex
     *
     * @param sex the value for tsp_caocao_custumer._sex
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._createtime
     *
     * @return the value of tsp_caocao_custumer._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._createtime
     *
     * @param createtime the value for tsp_caocao_custumer._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._updatetime
     *
     * @return the value of tsp_caocao_custumer._updatetime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._updatetime
     *
     * @param updatetime the value for tsp_caocao_custumer._updatetime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._author_update
     *
     * @return the value of tsp_caocao_custumer._author_update
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getAuthorUpdate() {
        return authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._author_update
     *
     * @param authorUpdate the value for tsp_caocao_custumer._author_update
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAuthorUpdate(String authorUpdate) {
        this.authorUpdate = authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._last_login_time
     *
     * @return the value of tsp_caocao_custumer._last_login_time
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Date getLastLoginTime() {
        return lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._last_login_time
     *
     * @param lastLoginTime the value for tsp_caocao_custumer._last_login_time
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._type
     *
     * @return the value of tsp_caocao_custumer._type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._type
     *
     * @param type the value for tsp_caocao_custumer._type
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._company
     *
     * @return the value of tsp_caocao_custumer._company
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._company
     *
     * @param company the value for tsp_caocao_custumer._company
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCompany(String company) {
        this.company = company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._company_address
     *
     * @return the value of tsp_caocao_custumer._company_address
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._company_address
     *
     * @param companyAddress the value for tsp_caocao_custumer._company_address
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._company_require
     *
     * @return the value of tsp_caocao_custumer._company_require
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getCompanyRequire() {
        return companyRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._company_require
     *
     * @param companyRequire the value for tsp_caocao_custumer._company_require
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCompanyRequire(Integer companyRequire) {
        this.companyRequire = companyRequire;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._invite_code
     *
     * @return the value of tsp_caocao_custumer._invite_code
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getInviteCode() {
        return inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._invite_code
     *
     * @param inviteCode the value for tsp_caocao_custumer._invite_code
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setInviteCode(String inviteCode) {
        this.inviteCode = inviteCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._citycode
     *
     * @return the value of tsp_caocao_custumer._citycode
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getCitycode() {
        return citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._citycode
     *
     * @param citycode the value for tsp_caocao_custumer._citycode
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCitycode(Integer citycode) {
        this.citycode = citycode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._areacode
     *
     * @return the value of tsp_caocao_custumer._areacode
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Integer getAreacode() {
        return areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._areacode
     *
     * @param areacode the value for tsp_caocao_custumer._areacode
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setAreacode(Integer areacode) {
        this.areacode = areacode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._version
     *
     * @return the value of tsp_caocao_custumer._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._version
     *
     * @param version the value for tsp_caocao_custumer._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_custumer._remark
     *
     * @return the value of tsp_caocao_custumer._remark
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_custumer._remark
     *
     * @param remark the value for tsp_caocao_custumer._remark
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}