package com.caocao.core.model;

public class DriverPic {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_img._driver_id
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_img._front_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    private String frontPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_img._back_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    private String backPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_img._licence_front_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    private String licenceFrontPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_img._licence_back_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    private String licenceBackPhoto;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_img._driver_id
     *
     * @return the value of tsp_caocao_driver_img._driver_id
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_img._driver_id
     *
     * @param driverId the value for tsp_caocao_driver_img._driver_id
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_img._front_photo
     *
     * @return the value of tsp_caocao_driver_img._front_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public String getFrontPhoto() {
        return frontPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_img._front_photo
     *
     * @param frontPhoto the value for tsp_caocao_driver_img._front_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public void setFrontPhoto(String frontPhoto) {
        this.frontPhoto = frontPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_img._back_photo
     *
     * @return the value of tsp_caocao_driver_img._back_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public String getBackPhoto() {
        return backPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_img._back_photo
     *
     * @param backPhoto the value for tsp_caocao_driver_img._back_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public void setBackPhoto(String backPhoto) {
        this.backPhoto = backPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_img._licence_front_photo
     *
     * @return the value of tsp_caocao_driver_img._licence_front_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public String getLicenceFrontPhoto() {
        return licenceFrontPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_img._licence_front_photo
     *
     * @param licenceFrontPhoto the value for tsp_caocao_driver_img._licence_front_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public void setLicenceFrontPhoto(String licenceFrontPhoto) {
        this.licenceFrontPhoto = licenceFrontPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_img._licence_back_photo
     *
     * @return the value of tsp_caocao_driver_img._licence_back_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public String getLicenceBackPhoto() {
        return licenceBackPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_img._licence_back_photo
     *
     * @param licenceBackPhoto the value for tsp_caocao_driver_img._licence_back_photo
     *
     * @mbggenerated Wed Jun 17 22:47:04 CST 2015
     */
    public void setLicenceBackPhoto(String licenceBackPhoto) {
        this.licenceBackPhoto = licenceBackPhoto;
    }
}