package com.caocao.core.model;

import java.util.Date;

public class DriverBillInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._order_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String orderId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._start_price
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double startPrice;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._distance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double distance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._driver_minute
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double driverMinute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._distance_per
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double distancePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._distance_time_per
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double distanceTimePer;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._cost_money
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double costMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._cost_real_money
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double costRealMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._privilege_code
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String privilegeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._destination_gap
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String destinationGap;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._cost_other
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double costOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._driver_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private String driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driver_bill_info._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._order_id
     *
     * @return the value of tsp_caocao_driver_bill_info._order_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._order_id
     *
     * @param orderId the value for tsp_caocao_driver_bill_info._order_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._start_price
     *
     * @return the value of tsp_caocao_driver_bill_info._start_price
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getStartPrice() {
        return startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._start_price
     *
     * @param startPrice the value for tsp_caocao_driver_bill_info._start_price
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setStartPrice(Double startPrice) {
        this.startPrice = startPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._distance
     *
     * @return the value of tsp_caocao_driver_bill_info._distance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getDistance() {
        return distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._distance
     *
     * @param distance the value for tsp_caocao_driver_bill_info._distance
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDistance(Double distance) {
        this.distance = distance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._driver_minute
     *
     * @return the value of tsp_caocao_driver_bill_info._driver_minute
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getDriverMinute() {
        return driverMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._driver_minute
     *
     * @param driverMinute the value for tsp_caocao_driver_bill_info._driver_minute
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDriverMinute(Double driverMinute) {
        this.driverMinute = driverMinute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._distance_per
     *
     * @return the value of tsp_caocao_driver_bill_info._distance_per
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getDistancePer() {
        return distancePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._distance_per
     *
     * @param distancePer the value for tsp_caocao_driver_bill_info._distance_per
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDistancePer(Double distancePer) {
        this.distancePer = distancePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._distance_time_per
     *
     * @return the value of tsp_caocao_driver_bill_info._distance_time_per
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getDistanceTimePer() {
        return distanceTimePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._distance_time_per
     *
     * @param distanceTimePer the value for tsp_caocao_driver_bill_info._distance_time_per
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDistanceTimePer(Double distanceTimePer) {
        this.distanceTimePer = distanceTimePer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._cost_money
     *
     * @return the value of tsp_caocao_driver_bill_info._cost_money
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getCostMoney() {
        return costMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._cost_money
     *
     * @param costMoney the value for tsp_caocao_driver_bill_info._cost_money
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCostMoney(Double costMoney) {
        this.costMoney = costMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._cost_real_money
     *
     * @return the value of tsp_caocao_driver_bill_info._cost_real_money
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getCostRealMoney() {
        return costRealMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._cost_real_money
     *
     * @param costRealMoney the value for tsp_caocao_driver_bill_info._cost_real_money
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCostRealMoney(Double costRealMoney) {
        this.costRealMoney = costRealMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._privilege_code
     *
     * @return the value of tsp_caocao_driver_bill_info._privilege_code
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getPrivilegeCode() {
        return privilegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._privilege_code
     *
     * @param privilegeCode the value for tsp_caocao_driver_bill_info._privilege_code
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setPrivilegeCode(String privilegeCode) {
        this.privilegeCode = privilegeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._destination_gap
     *
     * @return the value of tsp_caocao_driver_bill_info._destination_gap
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getDestinationGap() {
        return destinationGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._destination_gap
     *
     * @param destinationGap the value for tsp_caocao_driver_bill_info._destination_gap
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDestinationGap(String destinationGap) {
        this.destinationGap = destinationGap;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._createtime
     *
     * @return the value of tsp_caocao_driver_bill_info._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._createtime
     *
     * @param createtime the value for tsp_caocao_driver_bill_info._createtime
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._cost_other
     *
     * @return the value of tsp_caocao_driver_bill_info._cost_other
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getCostOther() {
        return costOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._cost_other
     *
     * @param costOther the value for tsp_caocao_driver_bill_info._cost_other
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setCostOther(Double costOther) {
        this.costOther = costOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._driver_id
     *
     * @return the value of tsp_caocao_driver_bill_info._driver_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public String getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._driver_id
     *
     * @param driverId the value for tsp_caocao_driver_bill_info._driver_id
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setDriverId(String driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driver_bill_info._version
     *
     * @return the value of tsp_caocao_driver_bill_info._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driver_bill_info._version
     *
     * @param version the value for tsp_caocao_driver_bill_info._version
     *
     * @mbggenerated Wed Jun 10 11:11:27 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}