package com.caocao.core.model;

import java.util.Date;

public class Driveaward {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._driver_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer driverId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._start_week
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer startWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._end_week
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer endWeek;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._start_interval
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Date startInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._end_interval
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Date endInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._multiple
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Double multiple;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._noweekend_max_give
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Double noweekendMaxGive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._weekend_max_give
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Double weekendMaxGive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Double version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_driveaward._remark
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._id
     *
     * @return the value of tsp_caocao_driveaward._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._id
     *
     * @param id the value for tsp_caocao_driveaward._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._driver_id
     *
     * @return the value of tsp_caocao_driveaward._driver_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getDriverId() {
        return driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._driver_id
     *
     * @param driverId the value for tsp_caocao_driveaward._driver_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setDriverId(Integer driverId) {
        this.driverId = driverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._start_week
     *
     * @return the value of tsp_caocao_driveaward._start_week
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getStartWeek() {
        return startWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._start_week
     *
     * @param startWeek the value for tsp_caocao_driveaward._start_week
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setStartWeek(Integer startWeek) {
        this.startWeek = startWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._end_week
     *
     * @return the value of tsp_caocao_driveaward._end_week
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getEndWeek() {
        return endWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._end_week
     *
     * @param endWeek the value for tsp_caocao_driveaward._end_week
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setEndWeek(Integer endWeek) {
        this.endWeek = endWeek;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._start_interval
     *
     * @return the value of tsp_caocao_driveaward._start_interval
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Date getStartInterval() {
        return startInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._start_interval
     *
     * @param startInterval the value for tsp_caocao_driveaward._start_interval
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setStartInterval(Date startInterval) {
        this.startInterval = startInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._end_interval
     *
     * @return the value of tsp_caocao_driveaward._end_interval
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Date getEndInterval() {
        return endInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._end_interval
     *
     * @param endInterval the value for tsp_caocao_driveaward._end_interval
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setEndInterval(Date endInterval) {
        this.endInterval = endInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._multiple
     *
     * @return the value of tsp_caocao_driveaward._multiple
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Double getMultiple() {
        return multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._multiple
     *
     * @param multiple the value for tsp_caocao_driveaward._multiple
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setMultiple(Double multiple) {
        this.multiple = multiple;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._noweekend_max_give
     *
     * @return the value of tsp_caocao_driveaward._noweekend_max_give
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Double getNoweekendMaxGive() {
        return noweekendMaxGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._noweekend_max_give
     *
     * @param noweekendMaxGive the value for tsp_caocao_driveaward._noweekend_max_give
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setNoweekendMaxGive(Double noweekendMaxGive) {
        this.noweekendMaxGive = noweekendMaxGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._weekend_max_give
     *
     * @return the value of tsp_caocao_driveaward._weekend_max_give
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Double getWeekendMaxGive() {
        return weekendMaxGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._weekend_max_give
     *
     * @param weekendMaxGive the value for tsp_caocao_driveaward._weekend_max_give
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setWeekendMaxGive(Double weekendMaxGive) {
        this.weekendMaxGive = weekendMaxGive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._version
     *
     * @return the value of tsp_caocao_driveaward._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._version
     *
     * @param version the value for tsp_caocao_driveaward._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_driveaward._remark
     *
     * @return the value of tsp_caocao_driveaward._remark
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_driveaward._remark
     *
     * @param remark the value for tsp_caocao_driveaward._remark
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }
}