package com.caocao.core.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_message._id
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_message._content
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_message._customer_id
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_message._title
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_message._create_time
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_message._version
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_message._id
     *
     * @return the value of tsp_caocao_message._id
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_message._id
     *
     * @param id the value for tsp_caocao_message._id
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_message._content
     *
     * @return the value of tsp_caocao_message._content
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_message._content
     *
     * @param content the value for tsp_caocao_message._content
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_message._customer_id
     *
     * @return the value of tsp_caocao_message._customer_id
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_message._customer_id
     *
     * @param customerId the value for tsp_caocao_message._customer_id
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_message._title
     *
     * @return the value of tsp_caocao_message._title
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_message._title
     *
     * @param title the value for tsp_caocao_message._title
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_message._create_time
     *
     * @return the value of tsp_caocao_message._create_time
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_message._create_time
     *
     * @param createTime the value for tsp_caocao_message._create_time
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_message._version
     *
     * @return the value of tsp_caocao_message._version
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_message._version
     *
     * @param version the value for tsp_caocao_message._version
     *
     * @mbggenerated Tue Jun 16 23:33:53 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}