package com.caocao.core.model;

import java.util.Date;

public class VipCompany {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._id
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._name
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._city_code
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String cityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._company_code
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String companyCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._master_name
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String masterName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._master_number
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String masterNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._contact_phone
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String contactPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._company_address
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String companyAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._is_valid
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private Integer isValid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._createtime
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._updatetime
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private Date updatetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._author_create
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String authorCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._author_update
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String authorUpdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._version
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private Double version;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_vipcompany._remark
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._id
     *
     * @return the value of tsp_caocao_vipcompany._id
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    
    private Date signDate;
    
    private Date signDateBegin;
    
    private Date signDateEnd;
    
    private String signDateStr;
    
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._id
     *
     * @param id the value for tsp_caocao_vipcompany._id
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._name
     *
     * @return the value of tsp_caocao_vipcompany._name
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._name
     *
     * @param name the value for tsp_caocao_vipcompany._name
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._city_code
     *
     * @return the value of tsp_caocao_vipcompany._city_code
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._city_code
     *
     * @param cityCode the value for tsp_caocao_vipcompany._city_code
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._company_code
     *
     * @return the value of tsp_caocao_vipcompany._company_code
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._company_code
     *
     * @param companyCode the value for tsp_caocao_vipcompany._company_code
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setCompanyCode(String companyCode) {
        this.companyCode = companyCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._master_name
     *
     * @return the value of tsp_caocao_vipcompany._master_name
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getMasterName() {
        return masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._master_name
     *
     * @param masterName the value for tsp_caocao_vipcompany._master_name
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setMasterName(String masterName) {
        this.masterName = masterName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._master_number
     *
     * @return the value of tsp_caocao_vipcompany._master_number
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getMasterNumber() {
        return masterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._master_number
     *
     * @param masterNumber the value for tsp_caocao_vipcompany._master_number
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setMasterNumber(String masterNumber) {
        this.masterNumber = masterNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._contact_phone
     *
     * @return the value of tsp_caocao_vipcompany._contact_phone
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getContactPhone() {
        return contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._contact_phone
     *
     * @param contactPhone the value for tsp_caocao_vipcompany._contact_phone
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setContactPhone(String contactPhone) {
        this.contactPhone = contactPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._company_address
     *
     * @return the value of tsp_caocao_vipcompany._company_address
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getCompanyAddress() {
        return companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._company_address
     *
     * @param companyAddress the value for tsp_caocao_vipcompany._company_address
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setCompanyAddress(String companyAddress) {
        this.companyAddress = companyAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._is_valid
     *
     * @return the value of tsp_caocao_vipcompany._is_valid
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public Integer getIsValid() {
        return isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._is_valid
     *
     * @param isValid the value for tsp_caocao_vipcompany._is_valid
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setIsValid(Integer isValid) {
        this.isValid = isValid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._createtime
     *
     * @return the value of tsp_caocao_vipcompany._createtime
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._createtime
     *
     * @param createtime the value for tsp_caocao_vipcompany._createtime
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._updatetime
     *
     * @return the value of tsp_caocao_vipcompany._updatetime
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._updatetime
     *
     * @param updatetime the value for tsp_caocao_vipcompany._updatetime
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._author_create
     *
     * @return the value of tsp_caocao_vipcompany._author_create
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getAuthorCreate() {
        return authorCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._author_create
     *
     * @param authorCreate the value for tsp_caocao_vipcompany._author_create
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setAuthorCreate(String authorCreate) {
        this.authorCreate = authorCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._author_update
     *
     * @return the value of tsp_caocao_vipcompany._author_update
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getAuthorUpdate() {
        return authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._author_update
     *
     * @param authorUpdate the value for tsp_caocao_vipcompany._author_update
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setAuthorUpdate(String authorUpdate) {
        this.authorUpdate = authorUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._version
     *
     * @return the value of tsp_caocao_vipcompany._version
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._version
     *
     * @param version the value for tsp_caocao_vipcompany._version
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_vipcompany._remark
     *
     * @return the value of tsp_caocao_vipcompany._remark
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_vipcompany._remark
     *
     * @param remark the value for tsp_caocao_vipcompany._remark
     *
     * @mbggenerated Thu Jun 18 13:20:28 CST 2015
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

	public Date getSignDate() {
		return signDate;
	}

	public void setSignDate(Date signDate) {
		this.signDate = signDate;
	}

	public Date getSignDateBegin() {
		return signDateBegin;
	}

	public void setSignDateBegin(Date signDateBegin) {
		this.signDateBegin = signDateBegin;
	}

	public Date getSignDateEnd() {
		return signDateEnd;
	}

	public void setSignDateEnd(Date signDateEnd) {
		this.signDateEnd = signDateEnd;
	}

	public String getSignDateStr() {
		return signDateStr;
	}

	public void setSignDateStr(String signDateStr) {
		this.signDateStr = signDateStr;
	}
}