package com.caocao.core.model;

public class CustomerInvitation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_customer_invitation._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_customer_invitation._customer_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer customerId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_customer_invitation._favored_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Integer favoredId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tsp_caocao_customer_invitation._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    private Double version;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_customer_invitation._id
     *
     * @return the value of tsp_caocao_customer_invitation._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_customer_invitation._id
     *
     * @param id the value for tsp_caocao_customer_invitation._id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_customer_invitation._customer_id
     *
     * @return the value of tsp_caocao_customer_invitation._customer_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_customer_invitation._customer_id
     *
     * @param customerId the value for tsp_caocao_customer_invitation._customer_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setCustomerId(Integer customerId) {
        this.customerId = customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_customer_invitation._favored_id
     *
     * @return the value of tsp_caocao_customer_invitation._favored_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Integer getFavoredId() {
        return favoredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_customer_invitation._favored_id
     *
     * @param favoredId the value for tsp_caocao_customer_invitation._favored_id
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setFavoredId(Integer favoredId) {
        this.favoredId = favoredId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tsp_caocao_customer_invitation._version
     *
     * @return the value of tsp_caocao_customer_invitation._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public Double getVersion() {
        return version;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tsp_caocao_customer_invitation._version
     *
     * @param version the value for tsp_caocao_customer_invitation._version
     *
     * @mbggenerated Tue Jun 16 10:42:40 CST 2015
     */
    public void setVersion(Double version) {
        this.version = version;
    }
}